### ISSUE TITLE
Tangle: message bundles are inconsistent

### ISSUE THREAD

**Issue by semenov-vladyslav** [iotaledger/streams#10] opened 2020-04-23 09:16 UTC
Bundles published with iota-lib-rs are inconsistent.

**Comment by JakeSCahill** [comment] 2020-04-23 13:04
This is caused by the issues mentioned here: https://github.com/iotaledger/iota.rs/issues

**Comment by JakeSCahill** [comment] 2020-05-05 11:48
I think we can close this now @semenov-vladyslav the problem was fixed in the Rust library.

**Closed** 2020-11-11 18:42 UTC
Labels: bug
